In [7]:
import numpy as np

### numpy创建数组

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.empty((2,2,3))

array([[[6.23042070e-307, 1.42417221e-306, 1.37961641e-306],
        [1.11261027e-306, 1.11261502e-306, 1.42410839e-306]],

       [[7.56597770e-307, 6.23059726e-307, 1.42419530e-306],
        [7.56602523e-307, 1.29061821e-306, 1.24610723e-306]]])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 矢量化
数组通常不用在编写循环的情况下就可以进行批量计算

In [8]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([2,4,6,8])
arr1 + arr2

array([ 3,  6,  9, 12])

In [11]:
arr1 = np.array([[1,2,3,4],[1,2,3,4]])
arr2 = np.array([[2,4,6,8],[3,5,7,9]])
print(arr1 + arr2)
print(arr1 * arr2)

[[ 3  6  9 12]
 [ 4  7 10 13]]
[[ 2  8 18 32]
 [ 3 10 21 36]]


In [13]:
5 * arr1

array([[ 5, 10, 15, 20],
       [ 5, 10, 15, 20]])

### numpy数组的索引和切片

In [16]:
arr = np.arange(10)
print(arr)
print(arr[2])
print(arr[0:4])

arr[0: 4] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
2
[0 1 2 3]
[12 12 12 12  4  5  6  7  8  9]
